### ISSUE TITLE
Plans for this package

### ISSUE THREAD

**Issue by mholt** [romain-jacotin/quic#1]
Hey Romain, I'm glad to see a pure Go implementation of QUIC popping up. Been keeping my eye on this and am really impressed at the quality of the commits so far. I know QUIC is still in flux (at least a little bit) but am wondering what your plans/timeline/goals are for this package. Unfortunately my hands are full right now, but if you plan on finishing it I'd definitely be interested in using it in one of my projects.

**Comment by ApfelUser** [comment]
+1

**Comment by romain-jacotin** [comment]
Hi Matt, my son have catched a complicated Lyme disease, this takes me out of this project until now. Rework on it in october.

**Comment by mholt** [comment]
Sorry to hear about your son. Take care; I pray that he will make a fast recovery!

**Comment by bharatkrishna** [comment]
@romain-jacotin hope your son has recovered now. I too am interested in knowing the progress of this project.

**Comment by lenovouser** [comment]
I second @bharatkrishna
